// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiQmLfFDBld6L2EIYsCzDTsTENh8ZRVAo',
    appId: '1:591701720649:web:52479e1a8c26a57f9e0998',
    messagingSenderId: '591701720649',
    projectId: 'htmlflutterpoc',
    authDomain: 'htmlflutterpoc.firebaseapp.com',
    storageBucket: 'htmlflutterpoc.appspot.com',
    measurementId: 'G-B10SNJYM49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBaoboUcOc6PwLZ99gBxnN-XK260cyafA',
    appId: '1:591701720649:android:cce2043b5ca81c3d9e0998',
    messagingSenderId: '591701720649',
    projectId: 'htmlflutterpoc',
    storageBucket: 'htmlflutterpoc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5-UlRyX2l1E1-K06BJFegjOgGds8BVvM',
    appId: '1:591701720649:ios:9b7d89c637227a8f9e0998',
    messagingSenderId: '591701720649',
    projectId: 'htmlflutterpoc',
    storageBucket: 'htmlflutterpoc.appspot.com',
    iosBundleId: 'com.example.flutterShoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5-UlRyX2l1E1-K06BJFegjOgGds8BVvM',
    appId: '1:591701720649:ios:9b7d89c637227a8f9e0998',
    messagingSenderId: '591701720649',
    projectId: 'htmlflutterpoc',
    storageBucket: 'htmlflutterpoc.appspot.com',
    iosBundleId: 'com.example.flutterShoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiQmLfFDBld6L2EIYsCzDTsTENh8ZRVAo',
    appId: '1:591701720649:web:71ddba9eb00104789e0998',
    messagingSenderId: '591701720649',
    projectId: 'htmlflutterpoc',
    authDomain: 'htmlflutterpoc.firebaseapp.com',
    storageBucket: 'htmlflutterpoc.appspot.com',
    measurementId: 'G-Q0T1E3ZP8N',
  );
}
